// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "@fhevm/solidity/lib/FHE.sol";
import "@fhevm/solidity/config/ZamaConfig.sol";

/// @title VaultCredit — Privacy-preserving on-chain credit scoring
/// @notice Computes credit scores entirely on encrypted inputs using Fully Homomorphic Encryption.
///         Raw financial data is never stored, transmitted, or visible to any party — not even
///         the contract owner. Lenders receive an encrypted boolean comparison result, never the score.
/// @dev Inherits ZamaEthereumConfig which auto-configures FHE coprocessor addresses for Sepolia (chainId 11155111)
///      and Ethereum mainnet (chainId 1) from ZamaConfig.sol.
contract VaultCredit is ZamaEthereumConfig {

    // ─── Storage ────────────────────────────────────────────────────────────────

    struct CreditProfile {
        euint32  score;        // Encrypted score — ciphertext handle, meaningless without decryption key
        uint256  lastUpdated;  // Block timestamp of last score computation
        bool     exists;       // Whether this address has computed a score
    }

    mapping(address => CreditProfile) private profiles;

    // ─── Scoring constants (plaintext — these weights are public knowledge) ─────

    uint32 private constant BASE_SCORE             = 500;   // Everyone starts at 500
    uint32 private constant MAX_SCORE              = 850;   // FICO-style ceiling
    uint32 private constant MIN_SCORE              = 300;   // Floor to prevent underflow wraparound
    uint32 private constant INCOME_DIVISOR         = 1000;  // $1k monthly income → +1 pt
    uint32 private constant MAX_INCOME_BONUS       = 150;   // Income bonus capped at +150 pts
    uint32 private constant DEBT_DIVISOR           = 2000;  // $2k debt → −1 pt
    uint32 private constant MAX_DEBT_PENALTY       = 200;   // Debt penalty capped at −200 pts
    uint32 private constant PAYMENT_PENALTY        = 20;    // 20 pts per missed payment
    uint32 private constant MAX_MISSED_PAYMENTS    = 12;    // Cap input at 12 (1 year)
    uint32 private constant MAX_EMPLOYMENT_MONTHS  = 60;    // Employment bonus caps at 5 years
    uint32 private constant EMPLOYMENT_MULTIPLIER  = 2;     // 2 pts per month of employment

    // ─── Events ──────────────────────────────────────────────────────────────────

    /// @notice Emitted when a user's encrypted score is stored; score itself is not revealed
    event ScoreComputed(address indexed user, uint256 timestamp);

    /// @notice Emitted when a lender requests a threshold comparison
    event ThresholdChecked(address indexed lender, address indexed user, uint256 timestamp);

    // ─── External functions ──────────────────────────────────────────────────────

    /**
     * @notice Submit encrypted financial data to compute and store your credit score.
     *         All four values share one inputProof, verified in a single coprocessor round trip.
     *
     * @param encryptedIncome           Encrypted monthly income in USD (externalEuint32 handle)
     * @param encryptedDebt             Encrypted total outstanding debt in USD (externalEuint32 handle)
     * @param encryptedMissedPayments   Encrypted missed/late payments in last 12 months (externalEuint32 handle)
     * @param encryptedEmploymentMonths Encrypted months of continuous employment (externalEuint32 handle)
     * @param inputProof                ZK proof generated by fhevmjs, validating all four inputs
     */
    function submitFinancialData(
        externalEuint32 encryptedIncome,
        externalEuint32 encryptedDebt,
        externalEuint32 encryptedMissedPayments,
        externalEuint32 encryptedEmploymentMonths,
        bytes calldata inputProof
    ) external {
        // Convert external handles → typed FHE values, verifying the bundled proof
        euint32 income           = FHE.fromExternal(encryptedIncome,           inputProof);
        euint32 debt             = FHE.fromExternal(encryptedDebt,             inputProof);
        euint32 missedPayments   = FHE.fromExternal(encryptedMissedPayments,   inputProof);
        euint32 employmentMonths = FHE.fromExternal(encryptedEmploymentMonths, inputProof);

        // Run all scoring logic entirely in FHE — plaintext is never produced at any step
        euint32 score = _computeScore(income, debt, missedPayments, employmentMonths);

        // Persist encrypted score — contract stores only the ciphertext handle
        profiles[msg.sender].score       = score;
        profiles[msg.sender].lastUpdated = block.timestamp;
        profiles[msg.sender].exists      = true;

        // ACL: contract retains access for future threshold comparisons
        FHE.allowThis(score);
        // ACL: user can decrypt their own score via the Zama gateway
        FHE.allow(score, msg.sender);

        emit ScoreComputed(msg.sender, block.timestamp);
    }

    /**
     * @notice Testnet demo entry point — accepts plain uint values, computes the score
     *         in plaintext using the identical formula as _computeScore(), then stores
     *         the result as an FHE-encrypted euint32 via FHE.asEuint32().
     *
     * @dev Intended for bounty judges / demo use where the Zama relayer SDK ACL
     *      pre-flight blocks client-side createEncryptedInput() on fresh wallets.
     *      The on-chain FHE data model is identical — the score is stored encrypted
     *      and all existing view/threshold functions work against it unchanged.
     *
     * @param income     Monthly income in USD (plain uint32)
     * @param debt       Total outstanding debt in USD (plain uint32)
     * @param missed     Missed payments in last 12 months (0–12)
     * @param employment Months of continuous employment (plain uint32)
     */
    function submitCreditDataMock(
        uint32 income,
        uint32 debt,
        uint32 missed,
        uint32 employment
    ) external {
        require(missed <= MAX_MISSED_PAYMENTS, "VaultCredit: missed payments must be 0-12");

        // ── Identical scoring formula to _computeScore(), in plaintext ────────────

        uint32 score = BASE_SCORE;

        // Income bonus
        uint32 incomeBonus = income / INCOME_DIVISOR;
        if (incomeBonus > MAX_INCOME_BONUS) incomeBonus = MAX_INCOME_BONUS;
        score += incomeBonus;

        // Debt penalty — guarded against underflow below MIN_SCORE
        uint32 debtPenalty = debt / DEBT_DIVISOR;
        if (debtPenalty > MAX_DEBT_PENALTY) debtPenalty = MAX_DEBT_PENALTY;
        if (score >= debtPenalty + MIN_SCORE) {
            score -= debtPenalty;
        } else {
            score = MIN_SCORE;
        }

        // Missed payment penalty — guarded against underflow below MIN_SCORE
        uint32 cappedMissed   = missed < MAX_MISSED_PAYMENTS ? missed : MAX_MISSED_PAYMENTS;
        uint32 paymentPenalty = cappedMissed * PAYMENT_PENALTY;
        if (score >= paymentPenalty + MIN_SCORE) {
            score -= paymentPenalty;
        } else {
            score = MIN_SCORE;
        }

        // Employment bonus
        uint32 cappedMonths    = employment < MAX_EMPLOYMENT_MONTHS ? employment : MAX_EMPLOYMENT_MONTHS;
        score += cappedMonths * EMPLOYMENT_MULTIPLIER;

        // Final ceiling
        if (score > MAX_SCORE) score = MAX_SCORE;

        // Wrap the plaintext result in an FHE ciphertext — same storage path as the
        // full FHE flow; checkCreditThreshold() and getEncryptedScore() work unchanged
        euint32 encryptedScore = FHE.asEuint32(score);

        profiles[msg.sender].score       = encryptedScore;
        profiles[msg.sender].lastUpdated = block.timestamp;
        profiles[msg.sender].exists      = true;

        FHE.allowThis(encryptedScore);
        FHE.allow(encryptedScore, msg.sender);

        emit ScoreComputed(msg.sender, block.timestamp);
    }

    /**
     * @notice Lender requests whether a borrower's score meets an encrypted threshold.
     *         Neither the actual score nor the threshold is decryptable by any other party —
     *         the lender receives only an encrypted boolean result.
     *
     * @param user               Borrower address to evaluate
     * @param encryptedThreshold Lender's minimum acceptable credit score (encrypted)
     * @param inputProof         ZK proof for the threshold value
     * @return meetsThreshold    Encrypted boolean — true if score ≥ threshold
     */
    function checkCreditThreshold(
        address user,
        externalEuint32 encryptedThreshold,
        bytes calldata inputProof
    ) external returns (ebool) {
        require(profiles[user].exists, "VaultCredit: no score on record for this address");

        euint32 threshold = FHE.fromExternal(encryptedThreshold, inputProof);

        // FHE comparison — result is an encrypted boolean, never a plaintext
        ebool meetsThreshold = FHE.ge(profiles[user].score, threshold);

        // Grant caller transient ACL access to decrypt the boolean within this transaction
        FHE.allowTransient(meetsThreshold, msg.sender);

        emit ThresholdChecked(msg.sender, user, block.timestamp);
        return meetsThreshold;
    }

    // ─── View functions ───────────────────────────────────────────────────────────

    /**
     * @notice Returns the encrypted score handle for a user.
     *         The caller must be on the ACL (i.e. be the score owner) to decrypt it.
     */
    function getEncryptedScore(address user) external view returns (euint32) {
        require(profiles[user].exists, "VaultCredit: no score on record for this address");
        return profiles[user].score;
    }

    /// @notice Returns whether an address has a stored credit score
    function hasScore(address user) external view returns (bool) {
        return profiles[user].exists;
    }

    /// @notice Returns the block timestamp when the user's score was last computed
    function getLastUpdated(address user) external view returns (uint256) {
        require(profiles[user].exists, "VaultCredit: no score on record for this address");
        return profiles[user].lastUpdated;
    }

    // ─── Internal FHE scoring logic ───────────────────────────────────────────────

    /**
     * @dev Computes a credit score from four encrypted inputs.
     *      All arithmetic is performed in FHE — intermediate values are ciphertexts.
     *      Underflow is prevented via FHE.select guards rather than plaintext branches.
     *
     * Scoring formula (encrypted throughout):
     *   score = 500 (base)
     *         + min(income / 1000, 150)            — income bonus      (max +150)
     *         − min(debt / 2000, 200)               — debt penalty      (max −200)
     *         − min(missedPayments, 12) × 20        — payment penalty   (max −240)
     *         + min(employmentMonths, 60) × 2       — employment bonus  (max +120)
     *   clamped to [300, 850]
     */
    function _computeScore(
        euint32 income,
        euint32 debt,
        euint32 missedPayments,
        euint32 employmentMonths
    ) internal returns (euint32) {

        // ── Base score ────────────────────────────────────────────────────────────
        euint32 score = FHE.asEuint32(BASE_SCORE);

        // ── Income bonus (up to +150 pts) ─────────────────────────────────────────
        // Divide encrypted income by $1000; e.g. $8k/month → +8 pts
        euint32 rawIncomeBonus = FHE.div(income, INCOME_DIVISOR);
        euint32 incomeBonus    = FHE.min(rawIncomeBonus, FHE.asEuint32(MAX_INCOME_BONUS));
        score = FHE.add(score, incomeBonus);

        // ── Debt penalty (up to −200 pts) ─────────────────────────────────────────
        // Divide encrypted total debt by $2000; e.g. $50k debt → −25 pts
        euint32 rawDebtPenalty = FHE.div(debt, DEBT_DIVISOR);
        euint32 debtPenalty    = FHE.min(rawDebtPenalty, FHE.asEuint32(MAX_DEBT_PENALTY));

        // Underflow guard: only subtract if result stays ≥ MIN_SCORE
        // safeDebt = (score >= debtPenalty + MIN_SCORE)
        ebool safeDebt = FHE.ge(score, FHE.add(debtPenalty, FHE.asEuint32(MIN_SCORE)));
        score = FHE.select(safeDebt, FHE.sub(score, debtPenalty), FHE.asEuint32(MIN_SCORE));

        // ── Missed payment penalty (20 pts each, up to −240 pts) ─────────────────
        euint32 cappedMissed   = FHE.min(missedPayments, FHE.asEuint32(MAX_MISSED_PAYMENTS));
        euint32 paymentPenalty = FHE.mul(cappedMissed, FHE.asEuint32(PAYMENT_PENALTY));

        ebool safePayment = FHE.ge(score, FHE.add(paymentPenalty, FHE.asEuint32(MIN_SCORE)));
        score = FHE.select(safePayment, FHE.sub(score, paymentPenalty), FHE.asEuint32(MIN_SCORE));

        // ── Employment stability bonus (+2 pts/month, max 60 months = +120) ───────
        euint32 cappedMonths    = FHE.min(employmentMonths, FHE.asEuint32(MAX_EMPLOYMENT_MONTHS));
        euint32 employmentBonus = FHE.mul(cappedMonths, FHE.asEuint32(EMPLOYMENT_MULTIPLIER));
        score = FHE.add(score, employmentBonus);

        // ── Final ceiling ──────────────────────────────────────────────────────────
        score = FHE.min(score, FHE.asEuint32(MAX_SCORE));

        return score;
    }
}
